name: Auto-Approve Pull Request
on:
 issue_comment:
   types: [created]
jobs:
 auto-approve:
   runs-on: ubuntu-latest
   if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '-APPROVED-') }}
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Approve Pull Request
       env:
         GH_TOKEN: ${{ secrets.APPROVER_TOKEN }}
       run: |
         gh pr review ${{ github.event.issue.number }} --approve -R ${{ github.repository }}
